### ISSUE TITLE
Texture for Diamond BEE its only Black and Purple.

### ISSUE THREAD

**Issue by RickyGeo** [Resourceful-Bees/ResourcefulBees#105]
If this is about a specific bee please report to the pack dev as we do not create bees we just give tools to pack devs.
If you do report a "bug" that is about a specific bee or set of bees it will be instantly closed due to it most likely being
an issue with the bees that pack devs added themself and not our code.
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots or Crash Logs**
If applicable, add screenshots or crash logs to help explain your problem.

**please complete the following information:**
 - Forge Version ahh still new
![2021-01-03_04 56 55]

 - Mod Version NEW one

**Additional context**
(https://user-images.githubusercontent.com/49329363/103466444-3bd68800-4d80-11eb-97c0-3f930707e9b4.png)

**Comment by RickyGeo** [comment]
and dosnt produse anyting xD

**Comment by RickyGeo** [comment]
1 more they mising after i put in out on bee jar faster  xD

**Comment by ThatGravyboat** [comment]
Are you using an old bee json? because the only way the bee would do that is if you are using an old bee json with a new system

**Comment by Epic428** [comment]
Yeah without more context we can’t resolve the issue.

**Comment by RickyGeo** [comment]
i use the new one

> Are you using an old bee json? because the only way the bee would do that is if you are using an old bee json with a new system

i use the new one..

**Comment by RickyGeo** [comment]
> Are you using an old bee json? because the only way the bee would do that is if you are using an old bee json with a new system

and how to del the old json and where to download the new one??

**Comment by Epic428** [comment]
Does your bee json look like the one in this link? 

https://resourceful-bees.readthedocs.io/en/1.16.3/default_bees/diamond/

The jsons are located in the bees folder in our Config folder.

**Comment by Vaerys-Dawn** [comment]
Please make sure your DiamondBee.Json texture stuff matches the one in the following link [here](https://resourceful-bees.readthedocs.io/en/1.16.3/default_bees/diamond/), and then try loading it again.
