### ISSUE TITLE
[Feature Request]: Generator fluid dumping

### ISSUE THREAD

**Issue by FoxTheUnicorn** [Resourceful-Bees/ResourcefulBees#269]
### Is your feature request related to a problem?

Generator is filled with 4 MB of a different honey type.

### Solution(s)

Like EnderIO when i place the generator in an empty crafting grid it should revert back to a default generator.

### Describe alternatives you've considered

A dump button or add support for the gauge dropper from Mekanism.

### Mod Version

1.16.5-0.6.7.2b

### Mod Loader Version

Forge - 36.2.0

### Acknowledgement

- [X] I agree that I read the terms at the top of the page.

**Comment by Epic428** [comment]
Hmmm that’s a pretty good suggestion. I will certainly add something like that for sure. Thanks for reporting!

**Comment by Vaerys-Dawn** [comment]
fixed in dev for 0.9.9.x
will be Implemented as a dump button in 1.0.0
