### ISSUE TITLE
[Bug]:  Resourceful Bees (resourcefulbees) has failed to load correctly

### ISSUE THREAD

**Issue by Gamer435YT** [Resourceful-Bees/ResourcefulBees#271]
### Bug Description

I wanted to start my server but after some time the following crash report appeared.

### Version

1.16.5-0.6.7.2b

### Mod Loader Version

36.2.0

### Logs or additional context

https://pastebin.com/CMq5wjZp

### Acknowledgement

- [x] I agree that I read the terms at the top of the page.

**Comment by ThatGravyBoat** [comment]
Your config has an error in it and forge cant parse the config

**Comment by Gamer435YT** [comment]
> Your config has an error in it and forge cant parse the config

And how can I fix that?

**Comment by ThatGravyBoat** [comment]
fix your config? I dont know what you changed in it crash logs only give you that your config couldn't be parsed because of the letter `f` after the word `honeycombHunate` apparently

**Comment by Gamer435YT** [comment]
> fix your config? I dont know what you changed in it crash logs only give you that your config couldn't be parsed because of the letter `f` after the word `honeycombHunate` apparently

I reuploadet all the serverfiles. Now it is working. Thank you. 👍
