### ISSUE TITLE
[Bug]: Glass Bottle Empty Duplicate

### ISSUE THREAD

**Issue by cocacolick** [Resourceful-Bees/ResourcefulBees#274]
### Bug Description

In the Manual Centrifuge with a Honey Block from minecraft it gives me 9 honey bottles and consumes me only one empty glass bottle.

So that once transformed into a block I find myself at +8 empty glass bottle.

I have not tested with Honey Block Customs

### Version

1.16.5-0.9.9.4

### Mod Loader Version

1.16.5-0.9.9.4

### Acknowledgement

- [X] I agree that I read the terms at the top of the page.

**Comment by Vaerys-Dawn** [comment]
Are you playing with a pack? Because the base mod does not add any recipes for the vanilla honey block in the centrifuge.

**Comment by ThatGravyBoat** [comment]
its not the recipes problem its that the mechanical centrifuge doesn't respect an output with a count greater than 1 for the bottle as we never really noticed as it was meant to be originally for only 1:1 but I must have missed the mechanical centrifuge when I fixed the normal one.

**Comment by ThatGravyBoat** [comment]
I just need to test my fix and then it will be pushed, and whenever we push a new fix update it will be included

**Comment by Vaerys-Dawn** [comment]
still, it shouldn't be giving 9 bottles, blocks are 4 bottles, or one bucket of honey, they should be using the honey tank and honey congealer

**Comment by ThatGravyBoat** [comment]
I think they may be talking about honeycomb block not honey block which is a recipe we have. Either way I'm fixing the bug it doesn't really matter as pack devs can change the standard from 4:1 to 9:1 with kube or ct

**Comment by ThatGravyBoat** [comment]
Its pushed and will be included in the next update or bug fix

**Comment by cocacolick** [comment]
I talk honeycomb Block vanilla, when i recipe honeycomb Block the manual centrifuge, the recipe consum 1 bottle glass empty for 9 honey bottle
