### ISSUE TITLE
Undefined Secondary Centrifuge Output Breaks Recipe Registration 

### ISSUE THREAD

**Issue by Ice-Arrow** [Resourceful-Bees/ResourcefulBees#277]
### Bug Description

A bee with a JSON which includes the "secondaryOutput" field but has "secondaryOutput" left unpopulated does not have the default of beeswax automatically supplied and does not have it's comb processing recipe registered on world load. 

### How to Reproduce?

1. Load a bee with an unpopulated "secondaryOutput" field (I have provided my iron bee JSON in the addition context box)
2. Check JEI for said bee's comb processing recipe or try to process that comb in a centrifuge (there should be no registered recipe if bug is reproduced)
3. Close minecraft and populate "secondaryOutput" with something, ex: minecraft:cobblestone
4. Load edited bee and check comb processing recipe (there should now be a recipe to process the comb where before there wasn't) 

### Expected Behavior

As per the wiki on Secondary Centrifuge Output "If no value is supplied then the default value of "Beeswax" is provided instead."

Beeswax should auto populate secondary output, or at the very least the recipe should register with only a primary output and no secondary.

### Version

1.16.5-0.9.9.4 (In my testing the bug also occurred on 1.16.5-0.6.7.2b)

### Mod Loader Version

1.16.5-36.1.2 (Bug also occurred on 1.16.5-36.2.0)

### Logs or additional context

**My Iron Bee JSON**
{
    "flower": "tag:forge:storage_blocks/iron",
    "maxTimeInHive": 2400,
    "traits": [""],
    "hasHoneycomb": true,
    "baseLayerTexture": "ores/iron/iron_bee",
    "ColorData": {
        "primaryColor": "#797979",
        "secondaryColor": "#ffcc99",
        "honeycombColor": "#ffcc99",
        "primaryLayerTexture": "empty_layer",
        "secondaryLayerTexture": "empty_layer",
        "emissiveLayerTexture": "empty_layer",
        "isBeeColored": false,
        "isRainbowBee": false,
        "isGlowing": false,
        "glowColor": "#ffcc99",
        "isEnchanted": false,
        "glowingPulse": 0,
        "modelType": "ORE"
    },
    "CombatData": {
        "isPassive": false,
        "removeStingerOnAttack": false,
        "inflictsPoison": true,
        "attackDamage": 1
    },
    "MutationData": {
        "hasMutation": false,
        "mutationCount": 1,
        "mutations": [{
                "type": "BLOCK_TO_ITEM",
                "inputID": "resourcefulbees:_honeycomb_block",
                "outputs": [{
                        "outputID": "",
                        "weight": 80
                    },
                    {
                        "outputID": "resourcefulbees:_bee_spawn_egg",
                        "weight": 20
                    }
                ]
            }
        ]
    },
    "CentrifugeData": {
        "hasCentrifugeOutput": true,
        "mainInputCount": 1,
        "mainOutput": "minecraft:iron_ore",
        "mainOutputWeight": 0.30,
        "mainOutputCount": 1,
        "mainNBTData": {},
        "secondaryOutput": "",
        "secondaryOutputWeight": 0.50,
        "secondaryOutputCount": 1,
        "secondaryNBTData": {},
        "bottleOutput": "minecraft:honey_bottle",
        "bottleOutputWeight": 0.20,
        "bottleOutputCount": 1,
        "bottleNBTData": {},
        "recipeTime": 200,
        "hasFluidOutput": false
    },
    "SpawnData": {
        "canSpawnInWorld": false,
        "biomeWhitelist": "",
        "biomeBlacklist": "",
        "spawnWeight": 8,
        "minYLevel": 0,
        "maxYLevel": 255,
        "minGroupSize": 1,
        "maxGroupSize": 3,
        "lightLevel": "ANY"
    },
    "BreedData": {
        "isBreedable": true,
        "parent1": "ashy_mining",
        "parent2": "leafcutter",
        "breedWeight": 10,
        "breedChance": 0.5,
        "feedItem": "minecraft:iron_ingot",
        "feedAmount": 1,
        "childGrowthDelay": -24000,
        "breedDelay": 6000
    },
    "TraitData": {
        "hasTraits": false
    }
}

**Before and After Debug Logs**

[Debug Before.log](https://github.com/Resourceful-Bees/ResourcefulBees/files/7150439/Debug.Before.log)
Check line 12Sep2021 15:51:23.310

[Debug After.log](https://github.com/Resourceful-Bees/ResourcefulBees/files/7150442/Debug.After.log)
Check line 12Sep2021 15:57:05.493

### Acknowledgement

- [X] I agree that I read the terms at the top of the page.

**Comment by Vaerys-Dawn** [comment]
not a bug, don't set "secondaryOutput" to "" bee registration sees that as something that it should look at, if you don't want a secondaryOutput don't put the value there at all just remove the line

**Comment by Epic428** [comment]
To clarify and add on to what dawn said. By not having the secondary output line we will default the output automatically. However to not have a secondary output at all you would need to use a data pack. In that case the bottle output would essentially become the secondary. Keep in mind this is all changing with our 1.0.0 mod rewrite.

**Comment by Ice-Arrow** [comment]
I see, removing the line entirely is what calls the default value of beeswax, NOT leaving the field blank. Thanks for the clarification now everything seems to be working, issue resolved :)
