### ISSUE TITLE
[Bug]: Resourceful Bees Breeder seems to reset its "breeder upgrade" on reload

### ISSUE THREAD

**Issue by TemperedFool** [Resourceful-Bees/ResourcefulBees#280]
### Bug Description

This is a report from one of our players [(link here)](https://github.com/NillerMedDild/Enigmatica6/issues/3227):

> Upon loading in the game, it is impossible to use the second breeding line offered by the breeder upgrade on a formed apiary (t1 in tests if it matters): the bees and materials are simply "pushed out" in the inventory (after a bit of time) or in world (if the GUI is closed) until the breeder upgrade is removed and reinserted. At that point, everything is peachy - until reload.
> 
> Didn't try to see if the order of the upgrades (one time and one breeder, in this order) matters, and didn't think to check if the time upgrade actually works on reload.

This is on the release version of the pack, so potentially it's already fixed in 0.9.9.x.

### Version

0.6.7.2b

### Mod Loader Version

36.2.2

### Logs or additional context

[latest.log](https://github.com/NillerMedDild/Enigmatica6/files/7150226/latest.log)

### Acknowledgement

- [X] I agree that I read the terms at the top of the page.

**Comment by ThatGravyBoat** [comment]
I think ive found the issue im testing and debugging now

**Comment by TemperedFool** [comment]
That is service - tbh, I expected this to present a challenge and/or a "sigh, this will be impossible to debug"!

**Comment by ThatGravyBoat** [comment]
ok ive fixed it. Ill talk to epic if there is anything to put out in a bug fix.

**Comment by ThatGravyBoat** [comment]
it was a simple mistake we only updated the slot count on the breeder on upgrade change but the client had the number of breeders so it could make the slots but the server didn't know they were valid so it just spits out the stuff it's like the crafting table how that has a container but it doesn't hold items on the server as hard data so it technically just "holds" the items until closed.
