### ISSUE TITLE
[Bug]: Unable to connect to Server

### ISSUE THREAD

**Issue by TritonJ73** [Resourceful-Bees/ResourcefulBees#283]
### Bug Description

Created a modpack, and whenever i try to connect to the server i set up for it, i get an error screen.
![image](https://user-images.githubusercontent.com/83465517/133686840-61c6eed3-b885-4070-a985-1327e9eaf500.png)
Internal Exeption: io.netty.handler.codec.EncoderException: java.lang.IllegalStateException: Modders must implement Ingredient.getSerializer in their custom Ingredients: com.resourcefulbees.resourcefulbees.recipe.HiveIngredient@1d1b7d4d

### Version

ResourcefulBees-1.16.5-0.9.9.5.jar

### Mod Loader Version

1.16.5 Forge - 36.2.0

### Acknowledgement

- [X] I agree that I read the terms at the top of the page.

**Comment by Epic428** [comment]
Already aware of the issue. I will be putting in a fix tonight and pushing a new update. Will need to use 0.9.9.4 for now

**Comment by TritonJ73** [comment]
Thanks!
