### ISSUE TITLE
[Bug]: Can't get honeycombs from beehives (with shears, or with scraper)

### ISSUE THREAD

**Issue by GreninjaSan** [Resourceful-Bees/ResourcefulBees#284]
### Bug Description

When using shears or scraper on a full beehive, no honeycombs are dropped.

### How to Reproduce?

1. Wait for a beehive (Tier 1, 2, 3 or 4) to be full
2. Click with shears on the beehive
3. Nothing is dropped.

### Expected Behavior

Honeycombs should be dropped.

### Version

0.9.9.6

### Mod Loader Version

1.16.5 - 36.2.0

### Logs or additional context

This also does not drop when using a dropper.

### Acknowledgement

- [X] I agree that I read the terms at the top of the page.

**Comment by Epic428** [comment]
Check common.toml the Config probably has the shears disabled but otherwise shears do work when the Config is enabled with the exception of modded shears. (That will be fixed)

**Comment by Epic428** [comment]
Also droppers don’t harvest hives. Dispensers do. And dispensers do work with our hives
