### ISSUE TITLE
[Bug]: Apiary visualizer checking for old block tag still

### ISSUE THREAD

**Issue by theboo** [Resourceful-Bees/ResourcefulBees#287]
### Bug Description

It seems the apiary visualizer is still checking for the old valid apiary block tag which no longer exists.

![image](https://user-images.githubusercontent.com/3585761/135770202-5ca9385c-4e6f-49be-bc7c-dd022899b42a.png)

### How to Reproduce?

place apiary block
enable visualizer
place valid block with collision 
notice it is still red

### Expected Behavior

visualizer should disappear in block space with a valid block

### Version

0.9.9.6

### Mod Loader Version

36.2.4

### Acknowledgement

- [X] I agree that I read the terms at the top of the page.

**Comment by Vaerys-Dawn** [comment]
fixed in dev
