### ISSUE TITLE
[Bug]: Apiary visualizer showing floor that shouldn't exist, and in the wrong location

### ISSUE THREAD

**Issue by theboo** [Resourceful-Bees/ResourcefulBees#288]
### Bug Description

The visualizer in the apiary block is currently showing a floor which is no longer part of the multiblock. Furthermore, it is showing the floor one block higher than it should be
![image](https://user-images.githubusercontent.com/3585761/135770345-1fea683a-3698-4203-88b9-ccb58620df2f.png)

### How to Reproduce?

place apiary block
show visualizer
notice the high floor

### Expected Behavior

should either bee no floor at all, or it should be in the correct spot :)

### Version

0.9.9.6

### Mod Loader Version

36.2.4

### Acknowledgement

- [X] I agree that I read the terms at the top of the page.

**Comment by yasiralamriki** [comment]
Correct me if I am wrong but you can adjust the position if that is what you mean

**Comment by Epic428** [comment]
No the preview is broken and literally shows the floor when it shouldn’t.

**Comment by Vaerys-Dawn** [comment]
fixed in dev
