### ISSUE TITLE
[Bug]: Vanilla Bees & Hives/Apiaries from Resourceful Bees - Enigmatica 6

### ISSUE THREAD

**Issue by TemperedFool** [Resourceful-Bees/ResourcefulBees#290]
### Bug Description

We've gotten [the following report](https://github.com/NillerMedDild/Enigmatica6/issues/3468)  from one of our players on Enigmatica 6. I haven't examined vanilla bee behavior with RBees stuff, so I was wondering if you guys know what we should expect. Reported issues:

1. Vanilla Honeycombs and Honeycomb Blocks do not show up as products (in JEI) of Hives/Apiaries from Resourceful Bees even though they can enter them and will produce Honeycombs/Honeycomb Blocks.

2. There also seem to be issues with vanilla bees re-entering an apiary without getting pollen from a flower. This results in no outputs being produced
(The bee exits the apiary for about one game tick and enters it again. The timer of the bee will be reduced to 600 ticks. After that it will leave again. This process seems to often repeat itself resulting in lower yields compared to other Bee Types (even if the other bee type has to spend more ticks inside an apiary to produce something).

3. They seem to forget their flower location after leaving an Apiary (Modded Bees always go to the same flower).

4. Vanilla Bees can not be bred through Resourceful Bees' Apiary Breeder.

I'm assuming 4 isn't implemented, and 1 is just assumed given vanilla bee behavior, but if you have other comments I'd appreciate them. For 2 and 3, this doesn't sound "proper" but I'm not sure.

Any feedback is appreciated, and if you need more info let me know!

### Version

0.9.9.6

### Mod Loader Version

1.16.5-36.2.4

### Acknowledgement

- [X] I agree that I read the terms at the top of the page.

**Comment by Epic428** [comment]
Yeah vanilla bee def doesn’t show up in jei. That can be fixed. Also we’ve heavily modified the logic for our bees. So it’s highly likely that the vanilla bee issues are simply because of mojangs shitty code. And yes if vanilla bees can’t breed with our bees then they won’t be able to breed in the breeder.

that aside I’ve implemented very little vanilla bee integration with our mods stuff and I have a few things I want to eventually explore so that vanilla bees can have deeper integration. However I prefer not to modify vanilla bees AI and cause them to work in unexpected ways since our primary goal is adding onto vanilla not necessarily changing vanilla.

**Comment by TemperedFool** [comment]
Heh, sounds fine; so if I'm reading correctly it sounds like issue 1 could be addressed, but the rest can't be fixed without messing with vanilla code you guys want to leave alone? That's easy enough to relay.

**Comment by Epic428** [comment]
Basically. Though I *may* consider making changes to the bees AI. Or at least using mixins to add whatever bits of logic I need for them to be able to breed with our bees.

**Comment by MrStatman80** [comment]
For Vanilla Bees use Thermal Expansion to automate it as they got a hive hopper now... it produces combs and honey.

With RS bees they can go into the centrifuge but only produce sugar and bee wax but use Thermal to automate it for combs and honey to upgrade

**Comment by MrStatman80** [comment]
> Yeah vanilla bee def doesn’t show up in jei. That can be fixed. Also we’ve heavily modified the logic for our bees. So it’s highly likely that the vanilla bee issues are simply because of mojangs shitty code. And yes if vanilla bees can’t breed with our bees then they won’t be able to breed in the breeder.
> 
> that aside I’ve implemented very little vanilla bee integration with our mods stuff and I have a few things I want to eventually explore so that vanilla bees can have deeper integration. However I prefer not to modify vanilla bees AI and cause them to work in unexpected ways since our primary goal is adding onto vanilla not necessarily changing vanilla.

If mojangg shitty code then why is this mod then?

Cos they knew someone would make it better by doing mobs

**Comment by Vaerys-Dawn** [comment]
closing due to #vanillaProblems
