### ISSUE TITLE
[Feature Request]: Camo for Apiaries

### ISSUE THREAD

**Issue by MuteTiefling** [Resourceful-Bees/ResourcefulBees#291]
### Is your feature request related to a problem?

Apiary blocks aren't always fitting to the décor one is going for. It would be nice if they could be disguised in some way. 

### Solution(s)

I think a simple way of handling this would be to have a 'camo' slot in the gui. You can insert any block into this slot and the apiary block will take on the texture of that block. 

### Mod Version

ResourcefulBees-1.16.5-0.9.9.8

### Mod Loader Version

1.16.5

### Additional context

<3

### Acknowledgement

- [X] I agree that I read the terms at the top of the page.

**Comment by Epic428** [comment]
Going to reference #295 for this one. new apiary design coming in the 1.0.0 update which would make the camo thing kinda useless/not possible as great of an idea as it is :)

**Comment by MuteTiefling** [comment]
cool, wasn't aware :D Thanks!
