### ISSUE TITLE
[Bug]: Apiary incorrectly displays exported message

### ISSUE THREAD

**Issue by yasiralamriki** [Resourceful-Bees/ResourcefulBees#292]
### Bug Description

Even if there is not a jar to export it will still display the successfully exported message.

### How to Reproduce?

1. Put bee(s) in apiary (if you have not already)
2. Click export (without jar available)
3. Done

### Expected Behavior

It shouldn't display the message at all

### Version

0.9.9.6

### Mod Loader Version

1.16.5 - 0.9.9.6

### Acknowledgement

- [X] I agree that I read the terms at the top of the page.

**Comment by Epic428** [comment]
Nice catch! I’ll look into that

**Comment by yasiralamriki** [comment]
sorry I read the message wrong, its small I have bad eyes

**Comment by Epic428** [comment]
Ah lmao no worries :)

**Comment by yasiralamriki** [comment]
I can turn this into a suggestion actually
