### ISSUE TITLE
[Bug]: Resourceful Bees Beehive de-tier when broken with Silktouch

### ISSUE THREAD

**Issue by Ridanisaurus** [Resourceful-Bees/ResourcefulBees#294]
### Bug Description

When breaking a Tiered Resourceful Bees Beehive (tiered with an item upgrade) with Silktouch (tested with Vanilla Silktouch, and both a Silktouch Pickaxe from Tetra, and Ars Nouveau spell using the Extract Glyph) returns the original Beehive, disregarding the tier upgrade applied to it.

### How to Reproduce?

1. Place Beehive
2. Tier it up with an upgrade
3. Break it with Silktouch
4. Broken Beehive loses the tier applied to it with the upgrade, and reverts back to its original state

### Expected Behavior

Either receiving an upgraded Beehive instead (so T1 Beehive + T2 Upgrade gives you T2 Beehive when broken), or you get back both the original Beehive, and the tier upgrade used, or have the broken Beehive maintain its blockstate.

### Version

ResourcefulBees-1.16.5-0.9.9.8

### Mod Loader Version

1.16.5 - 36.2.4

### Logs or additional context

N/A

### Acknowledgement

- [X] I agree that I read the terms at the top of the page.

**Comment by Epic428** [comment]
oooof seems like the look table isn't copying the nbt over for silk touch. I'll have to fix that, but also it can be fixed via data pack as well

**Comment by Ridanisaurus** [comment]
We will provide a temp fix from our side until then with KubeJS. Thanks.

**Comment by Epic428** [comment]
https://github.com/Resourceful-Bees/ResourcefulBees/blob/1.16.5/src/main/resources/data/resourcefulbees/loot_tables/blocks/t1_beehive.json

yeah it's just the tiered hives that are missing the silk touch entry in the loot table. however the nests do have the silktouch entires

**Comment by Epic428** [comment]
https://github.com/Resourceful-Bees/ResourcefulBees/blob/1.16.5/src/main/resources/data/resourcefulbees/loot_tables/blocks/acacia_bee_nest.json

here's the acacia nest with the correct entry for silk touch

**Comment by Vaerys-Dawn** [comment]
fixed in dev
