### ISSUE TITLE
[Feature Request]: Dying apiary blocks

### ISSUE THREAD

**Issue by yasiralamriki** [Resourceful-Bees/ResourcefulBees#295]
### Is your feature request related to a problem?

I feel as if the gray and bland apiary blocks should be able to be dyed as it would add more variety.

Also another reason:
Since AFAIK, you can have 4 apiaries in one multiblock (correct me if I am wrong), it would make it easier to know which one is which (you can color code it so you can have a black one for sooty bees or for bees that are colored black, etc this would work with all colors)

### Describe alternatives you've considered

Another option is a RGB or even RGBA customization along with or just the initial concept of having colors.

### Mod Version

0.9.9.6

### Mod Loader Version

1.16.5 - 0.9.9.6

### Acknowledgement

- [X] I agree that I read the terms at the top of the page.

**Comment by Epic428** [comment]
just gonna leave this here
![image](https://user-images.githubusercontent.com/291578/138340816-d5039010-295e-4fc3-b7fd-3bbf020abcac.png)

**Comment by yasiralamriki** [comment]
what

**Comment by Epic428** [comment]
new apiary design coming to a 1.0.0 update near you

**Comment by yasiralamriki** [comment]
nice
