### ISSUE TITLE
[Bug]: unable to craft apiary Tier 1

### ISSUE THREAD

**Issue by luneazur** [Resourceful-Bees/ResourcefulBees#296]
### Bug Description

On singleplayer session.

 All tiers recipes appears but if I try to craft tier 1 the items go in the correct slots but there's no apiary  in the result slot.

### How to Reproduce?

put ingredients into crafting station with the automatic button.

nothing appear.

### Expected Behavior

seeing the apiary crafted and being able to click to retrieve it.

### Version

0.9.9.6

### Mod Loader Version

1.16.5

### Logs or additional context

Tried to use minecraft vanilla Honeycomb/bee nest/ tried to use ressources from the same bee/ to use vanilla crafting station/ to do it manually. Nothing worked 

*sadness inside is growing up*😔 Help, pretty please with a lot of honey sweets on top.

### Acknowledgement

- [X] I agree that I read the terms at the top of the page.

**Comment by ThatGravyBoat** [comment]
update mod version

**Comment by luneazur** [comment]
Oh, Ok will try that thanks.

Envoyé à partir de Courrier pour Windows

De : ThatGravyBoat
Envoyé le :dimanche 24 octobre 2021 22:37
À : Resourceful-Bees/ResourcefulBees
Cc : luneazur; Author
Objet :Re: [Resourceful-Bees/ResourcefulBees] [Bug]: unable to craft apiary Tier 1 (Issue #296)

update mod version
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
