### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by SpoopyPumpkin** [Resourceful-Bees/ResourcefulBees#297]
### Bug Description

I'm currently playing on a server, Engimatica 6 for cursedforge. I started a new world and can no longer make and bee hives over tier one. It shows in the JEI, but when I go to craft it nothing shows up. The recipe is correct, but it hasn't worked in the last three restarts I've done. I'd appreciate help with this, advice on what to do and how to do it. Thankyou.

### Version

0.9.9.8

### Mod Loader Version

1.16.5

### Acknowledgement

- [X] I agree that I read the terms at the top of the page.

**Comment by ThatGravyBoat** [comment]
Update to the latest pack version which has the latest mod version

**Comment by SpoopyPumpkin** [comment]
The most recent version out is the one I have downloaded onto my server. Should I delete it and reinstall it ? Are there any conflicting mods that could affect resourceful bees from working properly ?

**Comment by TemperedFool** [comment]
@SpoopyPumpkin I suspect you're probably on 0.5.16, given the issue description; we've released 0.5.17 which should address these issues. It's currently marked as Beta, so make sure you're not just looking for the latest Release version.

**Comment by Epic428** [comment]
Use the in world upgrades as the recipes have been removed in favor of the prettier nests. This change is in preparation of the new mod update we’re working on.

**Comment by SpoopyPumpkin** [comment]
Thankyou guys so much for your response and helping me figure this out. I really appreciate your time & help. Its definitely my favorite mod, that's why I was so worried it wasn't working, ya'll are doing great work.
