### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ScummyD** [Resourceful-Bees/ResourcefulBees#299]
### Bug Description

unable to craft tier 2+ on Enigmatica 6

### Version

0.9.9.8

### Mod Loader Version

Forge 36.2.4

### Acknowledgement

- [X] I agree that I read the terms at the top of the page.

**Comment by Epic428** [comment]
Tier 2 + what? Hives? Apiaries? Based on the mod version listed I assume you need to update your pack version. Also note that in E6 they removed the hive recipes and instead you upgrade using in world upgrades.

**Comment by BvLiemt** [comment]
I had the same issue, make sure that the nest you're using is tier 2 (aka use an oddly-named 'hive-upgrade kit' on it)

**Comment by Epic428** [comment]
Curious. Why is it “oddly-named”? We use nest and hive interchangeably Bc even in vanilla there’s isn’t a difference beyond appearance.

**Comment by BvLiemt** [comment]
In the mod, 'bee hives' are the ones you craft, while 'nests' are the ones you find in the wild, but Im pretty sure the item is only used to upgrade nests.... I think

**Comment by Epic428** [comment]
It can do both. For now anyway

**Comment by Vaerys-Dawn** [comment]
probably a modpack issue likely already fixed, if it is still an issue and you are certain it is not a modpack issue let us know
