### ISSUE TITLE
[Bug]: Resourceful Bees only producing vanilla honeycombs

### ISSUE THREAD

**Issue by etherealgears** [Resourceful-Bees/ResourcefulBees#301]
### Bug Description

I'm using the mod straight out of the box, so I'm just playing with the default bees given by the mod, nothing custom. I have a green tier 1 beehive and two Diamond Bees in it that have a Diamond Block to pollinate. They pollinate the Diamond Block, fly into their hive and make honey, and then when the honey level reaches 5 I have a dispenser set up to automatically shear it. The problem is, when the dispenser shears the hive, regular vanilla honeycombs pop out, instead of the Diamond Honeycombs from Resourceful Bees. Both the Beepedia and JEI claim that Diamond Bees are meant to produce Diamond Honeycombs in hives, yet for some reason it's not working. I have tried with a pair of Gold Bees pollinating a Gold Block as well, and I get the exact same result.

### Version

0.9.9.8.

### Mod Loader Version

1.16.5. - 36.2.8.

### Acknowledgement

- [X] I agree that I read the terms at the top of the page.

**Comment by Epic428** [comment]
Are you using a vanilla hive/nest? If so vanilla hives will only produce vanilla combs. Also modded shears will cause vanilla combs to be produced as well

**Comment by etherealgears** [comment]
No, I am using the green Tier 1 Beehive from Resourceful Bees, and my dispensers are loaded with regular vanilla Minecraft shears. I did some additional testing, and shearing the hives manually while smoked does produce the correct modded combs. Furthermore, a scraper in the dispenser also produces the modded combs. It's only the specific case of using vanilla shears in a dispenser that produces vanilla combs.

**Comment by Vaerys-Dawn** [comment]
closing due to the fact that unless forge adds a whole way to register tools like shears as a type we can't really fix this
