### ISSUE TITLE
[Bug]: Lag from saving TieredBeehives

### ISSUE THREAD

**Issue by Darkere** [Resourceful-Bees/ResourcefulBees#302]
### Bug Description

Saving apiaries takes a long time if there are a lot of combs inside.

On this line `numberOfCombs()` seems to copy the list of all combs every iteration. 

https://github.com/Resourceful-Bees/ResourcefulBees/blob/d0185b195851d86f33ccdaec3294319b24094bc4/src/main/java/com/resourcefulbees/resourcefulbees/tileentity/TieredBeehiveTileEntity.java#L248

Spark report that shows the issue in practice: 

https://spark.lucko.me/gSGXLzjdGS

Screenshot in case the report expires: 
![image](https://user-images.githubusercontent.com/4283717/139830026-348e7b48-231c-4089-9bd5-28ed35d552b0.png)

### Version

github latest

### Mod Loader Version

any

### Acknowledgement

- [X] I agree that I read the terms at the top of the page.

**Comment by Epic428** [comment]
Thank you for the report! I’ll take a look at it as soon as I am able to. A bit busy this week as I just brought my baby home from the hospital on Sunday.

**Comment by ThatGravyBoat** [comment]
We can probs replace our current honeycomb storage system with a itemstackhandler, would also probs fix this issue and allow for less redundant code as we are essentially just making our own itemstack handler but using a queue system.

**Comment by Darkere** [comment]
I mean yes that will help, but for a quick fix just putting numberOfCombs() into a variable will already reduce the impact significantly. Evaluating that every iteration is just completely pointless.

**Comment by ThatGravyBoat** [comment]
ill port that back to the legacy branch later
