### ISSUE TITLE
[Bug]: Cannot Fill Empty Bottles With Honey From Non-Vanilla Nests

### ISSUE THREAD

**Issue by Extore** [Resourceful-Bees/ResourcefulBees#306]
### Bug Description

Honey bottles cannot be made from right clicking a smoked Resourceful Bees nest with an empty bottle, or by using a dispenser with empty bottles facing the nest. When attempting to do so, nothing happens, or in the case of the dispenser, an empty bottle is dispensed.

### How to Reproduce?

1. Set up a Resourceful Bees hive with a campfire underneath to make it "smoked"
2. Wait for nearby bees to pollinate nearby flowers and bring the hive to honey level 5
3. Attempt to fill an empty bottle by right clicking the hive

### Expected Behavior

When a Resourceful Bees nest reaches honey level 5, it is expected that right clicking with an empty bottle will produce a filled honey bottle and bring the honey level of the nest back down to where it first started.

### Version

0.9.9.8

### Mod Loader Version

1.16.5

### Logs or additional context

I am running the Enigmatica 6 modpack with Minecolonies added.

### Acknowledgement

- [X] I agree that I read the terms at the top of the page.

**Comment by Epic428** [comment]
Not a bug
