### ISSUE TITLE
[Bug]: Console Output from Honey Dipper showing lang key

### ISSUE THREAD

**Issue by TemperedFool** [Resourceful-Bees/ResourcefulBees#307]
### Bug Description

Reported to the E6 tracker: https://github.com/NillerMedDild/Enigmatica6/issues/3784

Apparently bees that autogenerate (Gold Bee in this example) display properly in the Honey Dipper's console output, while custom bees (in this example Rocky Bee) display the lang key.

Rocky Bee's lang entry is here: https://github.com/NillerMedDild/Enigmatica6/blob/master/config/resourcefulbees/resources/assets/resourcefulbees/lang/en_us.json#L300

### How to Reproduce?

1. Use the Honey Dipper on a Rocky bee
2. Check console output

### Expected Behavior

Would expect the bee's lang-based name to display.

### Version

0.9.9.8

### Mod Loader Version

36.2.4

### Acknowledgement

- [X] I agree that I read the terms at the top of the page.

**Comment by Vaerys-Dawn** [comment]
seems to be fixed in latest dev build

**Comment by Vaerys-Dawn** [comment]
uh, gotta test server side

**Comment by ThatGravyBoat** [comment]
its already fixed I just need to port it back

**Comment by Vaerys-Dawn** [comment]
appears to be fixed on server side

**Comment by Vaerys-Dawn** [comment]
on 1.16.5 build

**Comment by ThatGravyBoat** [comment]
it only happens with bees that pack devs add as the lang keys are only on the client side

**Comment by Vaerys-Dawn** [comment]
ah, i see

**Comment by ThatGravyBoat** [comment]
but its already fixed so when we do some updates for 1.16.5 ill backport it
