### ISSUE TITLE
[Bug]: Can't use honey bottles on my birch bee hive.

### ISSUE THREAD

**Issue by Turtl21** [Resourceful-Bees/ResourcefulBees#316]
### Bug Description

I right clicked on my beehive (which is full of honey, level 5 honey level) and it won't give me a bottle of honey. I tried everything, I even took my shield out of my offhand to see if that was the problem, but no results. Is this a bug or am I just doing something wrong because in vanilla Minecraft you just right click a bee's hive to collect the honey bottle, but this isn't working.

### How to Reproduce?

1. Use ATM 6.
2. Get a full birch bee hive.
2. Put a campfire under it.
3. Try to interact with a bottle.
4. No results will happen.

### Expected Behavior

When I click it it's supposed to give me a bottle of honey.

### Version

ResourcefulBees-1.16.5-0.9.9.8.jar

### Mod Loader Version

1.16.5

### Acknowledgement

- [X] I agree that I read the terms at the top of the page.

**Comment by Epic428** [comment]
It’s not a bug. It’s intentional

**Comment by Turtl21** [comment]
How do I get around it?

**Comment by Epic428** [comment]
Centrifuge recipes, beekeeper villager trades, vanilla beehives
