### ISSUE TITLE
[Bug]: join the world with the broken datapack tip.

### ISSUE THREAD

**Issue by magcicada** [Resourceful-Bees/ResourcefulBees#318]
### Bug Description

join the world with the broken datapack tip.

### Version

0.10.0

### Mod Loader Version

minecraft 1.16.5/forge 36.2.22

### Acknowledgement

- [X] I agree that I read the terms at the top of the page.

**Comment by Epic428** [comment]
Need more info. This is the least informative bug report

**Comment by magcicada** [comment]
just wait, I opening my computer again.

**Comment by magcicada** [comment]
just you will get this tip when join the old world  or create a new world.
![image](https://user-images.githubusercontent.com/45464670/147845407-c28d5b8a-9af5-4437-8980-3063384faa39.png)

**Comment by ThatGravyBoat** [comment]
send your latest.log

**Comment by magcicada** [comment]
[latest.log](https://github.com/Resourceful-Bees/ResourcefulBees/files/7797429/latest.log)

**Comment by Epic428** [comment]
![88BC7E39-1A44-4DE2-AA68-17CB28E1B244](https://user-images.githubusercontent.com/291578/147845483-6bf27797-db10-4152-ae8a-b9b610a1cae7.jpeg)

hmmm. This is at the end of the log. But there’s like 100 errors before this one about other json files and recipes.

**Comment by ThatGravyBoat** [comment]
its because Immersive Engineering creates their custom list of potions for their potion mixer thing on reload and it breaks because of how the tag potion recipe works

**Comment by Epic428** [comment]
So it’s an IE issue? If so I could try to reach out to malte

**Comment by ThatGravyBoat** [comment]
no not really its more of how stupid ingredients and tags work

**Comment by Epic428** [comment]
Ah ok

**Comment by magcicada** [comment]
just ok, I will have a look

**Comment by Epic428** [comment]
we're working on a fix that will get pushed here shortly

**Comment by magcicada** [comment]
Thx ver much.

**Comment by Vaerys-Dawn** [comment]
let me know asap if it doesn't work, build 0.10.1 should have the fix
