### ISSUE TITLE
[Bug]: Ticking block entity crash

### ISSUE THREAD

**Issue by bigenergy** [Resourceful-Bees/ResourcefulBees#319]
### Bug Description

Server crash

### Version

0.10.3

### Mod Loader Version

1.16.5-36.2.22

### Logs or additional context

https://gist.github.com/bigenergy/fa811cb5230b4bddaaad80c969efe5ee

### Acknowledgement

- [X] I agree that I read the terms at the top of the page.

**Comment by ThatGravyBoat** [comment]
Fixed in latest build, you can download it off of curse.
