### ISSUE TITLE
Beepedia crash on screen opening

### ISSUE THREAD

**Issue by AndreiTS** [Resourceful-Bees/ResourcefulBees#320]
### Bug Description

Right clicking with beepedia causes a null pointer exception.

### How to Reproduce?

1. Craft beepedia
2. right click on anything: air or a bee
3. game freezes and then crash

### Expected Behavior

Show information about the bee

### Version

1.16.5-0.10.3

### Mod Loader Version

1.16.5-36.2.23

### Logs or additional context

Crash report: https://paste.ee/p/f9AcP

### Acknowledgement

- [X] I agree that I read the terms at the top of the page.

**Comment by AndreiTS** [comment]
I tested without optifine but it crashed again: https://paste.ee/p/gfRd0

**Comment by ThatGravyBoat** [comment]
Fixed in latest build, you can download it off of curse.
