### ISSUE TITLE
[Bug]: honey congealer disappears when broken with atomic disassembler from mekanism

### ISSUE THREAD

**Issue by antrobot1234** [Resourceful-Bees/ResourcefulBees#321]
### Bug Description

exactly as the title states

### How to Reproduce?

1. install mek and resourceful bees
2. get an atomic disassembler and charge it
3. place down a honey congealer
4. break it with the disassembler
5. watch it dissapear

### Expected Behavior

for it to drop as an item

### Version

0.6.7.1b

### Mod Loader Version

36.1.0

### Acknowledgement

- [X] I agree that I read the terms at the top of the page.

**Comment by Epic428** [comment]
Update your mod version as it’s so far out of date. I’m certain this is already fixed
