### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by TheSupremeQuartz** [Resourceful-Bees/ResourcefulBees#322]
### Bug Description

The Apiary seems bugged and I'm not sure if it's because the modpack I'm running (FTB Ultimate: Anniversary Edition) or if the mod is just wigging out.  I watched a creator, EctorVynk, create an apiary using Beeswax blocks, Glass, and Glowstone and it was valid. When I tried to reproduce this exact same structure, everything came back invalid. I really do not want to build a structure out of only Apiary blocks, as that is incredibly resource heavy and is taking most, if not all of the fun out of the mod for me.

Failed Apiary attempt with bottom row of valid, Tier 1 apiary blocks.
![2022-01-21_16 31 46](https://user-images.githubusercontent.com/98192647/150610335-b5c6233b-7057-43a3-a2e9-5431dce32f91.png)
.
EctorVynk's video
https://www.youtube.com/watch?v=HfwNydVCFHk&ab_channel=EctorVynk

### How to Reproduce?

Try to build an apiary with any blocks except the Tier 1, 2, 3, or 4 hives, storage, or breeder blocks other than the required ones.
Validate the structure or enable the preview.
Any blocks that aren't the listed blocks are invalid.

### Expected Behavior

The Apiary is supposed to be valid and support the blocks used
![valid apiary](https://user-images.githubusercontent.com/98192647/150610509-afcd584e-1932-4e10-862b-0ca638575c97.png)
.

### Version

0.9.9.8

### Mod Loader Version

1.16.5-forge-36.2.22

### Acknowledgement

- [X] I agree that I read the terms at the top of the page.

**Comment by Vaerys-Dawn** [comment]
you can use any solid block to create the apiary structure, the structure is failing to validate because you've placed more than one apiary down. remove the extra apiaries, and try placing something like stone down

**Comment by Vaerys-Dawn** [comment]
there is a bug in 0.9.9.8 that shows incorrect validation, any solid block should do, even if it shows up in red.

**Comment by ThatGravyBoat** [comment]
Im pretty sure this was fixed in 0.10.0 so going to close.
