### ISSUE TITLE
[Bug]: Honey generator and Beecon void honey when disable enableEasterEggBees in config

### ISSUE THREAD

**Issue by frank89722** [Resourceful-Bees/ResourcefulBees#323]
### Bug Description

Honey generator and Beecon void honey input from honey bottle when `enableEasterEggBees` is set to `false` in common config.

### How to Reproduce?

1. Set `enableEasterEggBees` to false in common config
2. Enter a world and try to fill Honey generator or Beecon with honey bottle
3. Honey in the bottle got void

### Version

0.10.4

### Mod Loader Version

1.16.5-36.2.22

### Acknowledgement

- [X] I agree that I read the terms at the top of the page.

**Comment by Vaerys-Dawn** [comment]
Looking at this now, this seems really weird, and definitely shouldn't happen.

**Comment by Epic428** [comment]
Unless you added some sort of check for the Boolean to the logic in one of the recent updates. The only thing I can think of is the honey bottle being used doesn’t have a fluid variant for the bee in question. But tbh more information would be useful.

**Comment by Vaerys-Dawn** [comment]
I think i know why this is happening, it's because the tags related to honey aren't loading properly because starry honey doesn't exist

**Comment by Vaerys-Dawn** [comment]
should be an easy fix

**Comment by Vaerys-Dawn** [comment]
fixed in 0.10.5
