### ISSUE TITLE
[Bug]: Unable to Output from Apiary Storage

### ISSUE THREAD

**Issue by tumultkersplode** [Resourceful-Bees/ResourcefulBees#325]
### Bug Description

I am unable to output from my apiary storage using pipes or anything. This is on ATM6 1.8.17 using ResourcefulBees0.9.8

I've tried Mekanism Ultimate Logistical Transporters. I've tried Cyclic Item Transfer Nodes. I've tried Pipez Universal Pipe (not sure if that one even does items, but I'm desperate). I dug around in the config looking for some setting that got set to false and I don't see anything that would cause Resourceful Bees to not play nice with other mods.

### How to Reproduce?

1. Create Apiary multiblock.
2. Put a bee in there.
3. Make sure combs are going into storage.
4. Connect any output pipe to anything.
5. Nothing happens.

### Expected Behavior

I should be able to output my combs from my apiaries.

### Version

0.9.8

### Mod Loader Version

1.16.5

### Acknowledgement

- [X] I agree that I read the terms at the top of the page.

**Comment by Epic428** [comment]
I’m inclined to believe that the issue is on your end either not setting the pipes up right or something otherwise we’d have already been notified of the issue and fixed.

**Comment by tumultkersplode** [comment]
> I’m inclined to believe that the issue is on your end either not setting the pipes up right or something otherwise we’d have already been notified of the issue and fixed.

This is what I've been doing with the pipes. Just going straight from the Apiary Storage to the chest or Centrifuge.

edit: pay no mind to the extra storage. I was trying something out based on how the picture is on the in-game book.

![image](https://user-images.githubusercontent.com/98577699/151505755-1cb8a63d-734e-4d59-b740-1c0285192507.png)

**Comment by Epic428** [comment]
Well the extra storage block may have impacted which one is “linked” to the apiary. But that aside have you properly configured the mek cable connected to the storage block such that it is extracting?

**Comment by tumultkersplode** [comment]
> Well the extra storage block may have impacted which one is “linked” to the apiary. But that aside have you properly configured the mek cable connected to the storage block such that it is extracting?

Yeah, turns out I'm an idiot. I didn't realize there was a spot close to where the pipe connects with the block that you can shift click on to change whether it pushes or pulls. So sorry for wasting your time!

**Comment by Epic428** [comment]
No worries. At least you’ve got it working now :)
