### ISSUE TITLE
[Bug]: Can't craft hives

### ISSUE THREAD

**Issue by sharpskull2** [Resourceful-Bees/ResourcefulBees#327]
### Bug Description

In a creative world, I was testing with the latest version of resourceful bees and noticed that I could not craft any of the hives

### How to Reproduce?

1. Spawn in required ingredients to craft hive
2. Try to craft hive by putting the ingredients into the crafting table
3. No crafting output (even though jei shows that the recipe exists)

### Expected Behavior

Able to craft hives

### Version

1.16.5 - 0.10.4

### Mod Loader Version

1.16.5-36.2.20

### Acknowledgement

- [X] I agree that I read the terms at the top of the page.

**Comment by Shunnai** [comment]
Similar issue. ATM6 Cannot craft T1 Hives from vanilla nests or hives. Everything past that is fine

**Comment by Pdiddy973** [comment]
Fixed in https://github.com/AllTheMods/ATM-6/pull/2913, available next update
