### ISSUE TITLE
[Feature Request]: Update to Minecraft 1.18.1

### ISSUE THREAD

**Issue by PernDragon** [Resourceful-Bees/ResourcefulBees#328]
### Is your feature request related to a problem?

Please Update this awesome mode for 1.18.1, I'm sure you have probably been asked and are working on it but I couldn't find any info regarding that.  Thanks for your consideration on this matter, I look forward to trying your mod out once this takes place.
Thank you ever so much.

### Mod Version

N/A

### Mod Loader Version

Forge Latest

### Acknowledgement

- [X] I agree that I read the terms at the top of the page.

**Comment by Vaerys-Dawn** [comment]
already in development

**Comment by PernDragon** [comment]
A world of thanks to you.

**Comment by Niketats** [comment]
so, is 1.18 still planned?
