### ISSUE TITLE
[Feature Request]: Ability to edit easter egg bees

### ISSUE THREAD

**Issue by notWaterGuy12** [Resourceful-Bees/ResourcefulBees#330]
### Is your feature request related to a problem?

I want to disable the in-world spawning of easter egg/patreon bees, but I don't want to disable them completely. The only config option currently available is to disable them completely.

### Solution(s)

Just a config option to disable easter egg/patreon bees spawning in world would be good.

### Describe alternatives you've considered

There could also be exposed data files for the bees, like with the other types.

### Mod Version

0.10.5

### Mod Loader Version

1.16.5 -36.2.29

### Acknowledgement

- [X] I agree that I read the terms at the top of the page.

**Comment by Vaerys-Dawn** [comment]
already implemented, enableEasterEggBees = false in the config/resourcefulbees/common.toml file (also enableCustomPatreonBees for the AbBee)

also, the bee jsons for the easter egg bees can be found here: https://github.com/Resourceful-Bees/ResourcefulBees/tree/1.16.5/dev_resources/dev_jsons
