### ISSUE TITLE
Multiple Netherite Bees mutated from one Diamond bee

### ISSUE THREAD

**Issue by TemperedFool** [Resourceful-Bees/ResourcefulBees#333]
### Bug Description

See issue on the E6 issue tracker: https://github.com/EnigmaticaModpacks/Enigmatica6/issues/4631

Curiouser and Curiouser re: the duplicate netherite bee issue. Not sure if this helps narrow things down at all?

### Version

0.10.4

### Mod Loader Version

1.16.5-36.2.29

### Acknowledgement

- [X] I agree that I read the terms at the top of the page.

**Comment by ThatGravyBoat** [comment]
Duplicate of #314 We can keep the conversion going there but I think I figured out why this happens and I can have a build for some people to test and see if it still happens.
