### ISSUE TITLE
[Bug]: Bee forget its assigned apiary when using 2 apiary blocks in the same apiary space

### ISSUE THREAD

**Issue by Porcy** [Resourceful-Bees/ResourcefulBees#339]
### Bug Description

I want 2 of the same bee to produce at the same time. I put 2 apiary blocks and 2 apiary inventories. Validation successfull. I import each bee in a different apiary block. When they come out, they both want to go in the same apiary, making one of them having to wait for its turn. I was expecting each bee to remember their assigned apiary when importing them. Not sure how intended this behavior is though.

### How to Reproduce?

See description

### Expected Behavior

See description

### Version

0.10.6

### Mod Loader Version

1.16.5

### Acknowledgement

- [X] I agree that I read the terms at the top of the page.

**Comment by Epic428** [comment]
Nah this is intended behavior. The import/export option was so people could make apiaries without doors and still put their bees inside.

**Comment by Porcy** [comment]
Thanks. I'll design accordingly then...

**Comment by Epic428** [comment]
Yeah the way vanilla works bees tend to seek out the closest hive and don’t always remember the last hive they were in. Hive = Apiary in this case.
