### ISSUE TITLE
[Bug]: Little bee is really annoying and you cant disable it

### ISSUE THREAD

**Issue by Dwellisys** [Resourceful-Bees/ResourcefulBees#340]
### Bug Description

at all times theres a little bee circling every player with no option to disable

### How to Reproduce?

Download the mod

### Version

1.12

### Mod Loader Version

1.16.5

### Acknowledgement

- [X] I agree that I read the terms at the top of the page.

**Comment by ThatGravyBoat** [comment]
You can disable it with version 0.10.7 by editing the client config and the bee is no longer enabled anymore so you probs opened your game more than 2 hours ago because we only check if the default bee is on when the game first loads so you have the old pet configuration.
