### ISSUE TITLE
[Bug]: Tier 1 Beehive can't use vanilla beehive as base

### ISSUE THREAD

**Issue by Ayrshi** [Resourceful-Bees/ResourcefulBees#359]
### Bug Description

I'm sure I used the vanilla beehive to make tier 1 beehives, so I didn't have to go out into the world and look for 2000+ bee nests. That being said, I can't seem to do that anymore when I want to make more apiaries.

### Expected Behavior

![image](https://user-images.githubusercontent.com/116687320/197891602-e33ba740-a5dd-4880-9e51-47db0a8836d1.png)
No make Tier 1 beehive anymore. Is it supposed to be like that and I found the UNO reverse? Or is this the bug where it no make Tier 1 beehive?

### Version

1.16.5

### Mod Loader Version

36.2.39

### Acknowledgement

- [X] I agree that I read the terms at the top of the page.

**Comment by Epic428** [comment]
Yeah it seems the recipe in the mod has been broken for a very long time lmao. This week I have to push an update that includes a Chinese translation so I will make sure to fix this recipe as well
