### ISSUE TITLE
[Bug]:  Despawning Bees in side closure 1.19.2

### ISSUE THREAD

**Issue by SGZ-Creations** [Resourceful-Bees/ResourcefulBees#368]
### Bug Description

To Clarify this is the default bees following the mod.
![image](https://user-images.githubusercontent.com/59801736/228655734-b55a5b0b-f54a-4ff0-89fe-766ac2c48962.png)

Bees keep disappearing /despawning, they have the block or item they like in the enclosed area
![image](https://user-images.githubusercontent.com/59801736/228657466-f333e7dd-3c5a-493c-bdbf-481942fc4714.png)
Still the disappear

### How to Reproduce?

Technical:
1 set up a server with mod on.
2. Not sure if any errors really exists. If solve maybe these first?
3. join server and get started.

Play Testing:
1. Build enclosed area.
2. Capture ant type of bee.
3. Have them in this enclosed area with 3 or more nest. Harvest only 2 of 3 or more nest.
4. Leave server running over night.
5. log back on day after and see bees "bye bye" Despawned.  

### Expected Behavior

For them to not disappear/De-spawn when having them in enclosed room

### Version

1.0.0. Alpha

### Mod Loader Version

1.19.2

### Logs or additional context

[latest.log](https://github.com/Team-Resourceful/ResourcefulBees/files/11105266/latest.log)

### Acknowledgement

- [X] I agree that I read the terms at the top of the page.

**Comment by SGZ-Creations** [comment]
One reason may be due to not being chunk loaded

**Comment by Epic428** [comment]
Despawn logic was vastly improved in commit 88b4adf so that it follows vanilla more closely. Any bees captured and released via a bee jar won’t despawn
