### ISSUE TITLE
items not found in creative mode[Bug]: 

### ISSUE THREAD

**Issue by Netrecov** [Resourceful-Bees/ResourcefulBees#370]
### Bug Description

Loaded the mod, and went into creative to explore the mechaincs, and none of the items are on the last tab, or searchable by name.

### How to Reproduce?

load creative game, and search for items

### Expected Behavior

items should be returned in search or be in the list of the last tab.

### Version

10.7

### Mod Loader Version

1.16.5 

### Acknowledgement

- [X] I agree that I read the terms at the top of the page.

**Comment by ThatGravyBoat** [comment]
Works perfectly fine for me, you likely have another mod breaking it.
