### ISSUE TITLE
[Bug]: Quartz and Rgbee honeycomb not working server side

### ISSUE THREAD

**Issue by Rosenblack** [Resourceful-Bees/ResourcefulBees#371]
### Bug Description

So with only the mods required for this and jei (to check drops), neither the nether quartz or rgbee honeycomb hive drops exist when on a server, singleplayer, just fine.
they were working the other day and i cant seem to get it back to that state, every other bee seems to work just fine

### How to Reproduce?

Get required mods,
run server,
check drops

### Expected Behavior

Being able to obtain the combs

### Version

alpha 19

### Mod Loader Version

43.2.10

### Logs or additional context

heres the full log for that instance if you need it
https://pastebin.com/kSjRy1Mp

### Acknowledgement

- [X] I agree that I read the terms at the top of the page.

**Comment by Epic428** [comment]
In the general Config there is an option generateDefaults. Set that to true so the updated bee files get copied over and used. It will automatically switch back to false after the first run. You will have to restart the server for the changes to take effect too
