### ISSUE TITLE
[Bug]: apiary not working or idk how to use it

### ISSUE THREAD

**Issue by iamnoob999** [Resourceful-Bees/ResourcefulBees#372]
### Bug Description

i made a apiary and i was use to the old multiblock apiary but now its wired and hard to use im in 1.19. 2

### How to Reproduce?

1.place apiary
2.get confused

### Expected Behavior

i expected it to be understandable

### Version

1.19.2

### Mod Loader Version

43.2.8

### Acknowledgement

- [X] I agree that I read the terms at the top of the page.

**Comment by Epic428** [comment]
If you know how a standard hive works then you know how the apiary works. It just has a fancy model and an internal inventory and is no longer a multiblock. It also doesn’t have the unique bee limit either. Beyond that it functions exactly as any hive would

**Comment by iamnoob999** [comment]
so it just is a nest but wtih less time in the hive and auto harvesting?

**Comment by Epic428** [comment]
Basically yes.

**Comment by iamnoob999** [comment]
oh ok thanks

**Comment by Epic428** [comment]
Much faster. Holds way more bees. And has a large internal inventory
