### ISSUE TITLE
[Bug]: Centrifuge isnt processing combs

### ISSUE THREAD

**Issue by Rosenblack** [Resourceful-Bees/ResourcefulBees#374]
### Bug Description

Ive had it process thousands of combs but randomly it likes to stop, sometimes removing the input and readding it fixes it but ive fully automated it so that defeats the purpose of automation, had a talk with oreo in the discord and was told to post here as well.
all outputs were empty, inputs had a couple stacks of combs, no fluids blocking, had basically unlimited power, just didnt want to work
![image](https://user-images.githubusercontent.com/10399357/236720574-1899d91f-a768-466a-9617-de63dca22e34.png)
![image](https://user-images.githubusercontent.com/10399357/236720563-88aabbd8-fc31-422d-bc8d-57e5fabc4dd5.png)
![image](https://user-images.githubusercontent.com/10399357/236720589-6e3baee0-99a2-422e-a7d9-c68216461e30.png)
![image](https://user-images.githubusercontent.com/10399357/236720633-6db5eba6-df13-452d-90ca-f7f5f37f8ad7.png)
(some images from the discord convo)

### Expected Behavior

Being able to process combs reliably 

### Version

alpha 19

### Mod Loader Version

1.19.2 43.2.10

### Acknowledgement

- [X] I agree that I read the terms at the top of the page.

**Comment by BabyKiwii** [comment]
I have the same problem

**Comment by Epic428** [comment]
This was fixed in commit d1384b9
