### ISSUE TITLE
[Feature Request]: Config option to turn off flashing effect of radioactive bee

### ISSUE THREAD

**Issue by Trisscar05** [Resourceful-Bees/ResourcefulBees#381]
### Is your feature request related to a problem?

As the title. The flashing is actively uncomfortable to look at in NEI much less in the world itself. An option to turn off the flashing, or set it to something slower seems to be necessary and also absent.

Unless I just missed it in the ingame configs, which is always possible.

### Mod Version

0.10.7

### Mod Loader Version

1.16.5

### Acknowledgement

- [X] I agree that I read the terms at the top of the page.

**Comment by Epic428** [comment]
Radioactive bee is not a bee we provide by default. It is custom made by whichever pack you’re playing. The flashing is definitely configurable and would be part of the bee’s json file. You could double check the beeper for which value it is specifically as I don’t recall offhand

**Comment by Trisscar05** [comment]
Ahhh ok, thankee much, have a nice rest of your day.

**Comment by Trisscar05** [comment]
for those wondering who might need this later: the bee was added into this folder in the Sky Capsule pack:
/ATLauncher/instances/SkyCapsuleProject/config/resourcefulbees/bees/tier3

I have deleted these lines from the json:
    "isGlowing": true,
    "glowColor": "#00D65F",
    "glowingPulse": 2,

Edit: Yup that worked, now it just has a normal ore look to it. Luck to anyone else who finds this.
