### ISSUE TITLE
[Bug]: or request 

### ISSUE THREAD

**Issue by DevilMayCryIfrit** [Resourceful-Bees/ResourcefulBees#385]
### Bug Description

I let my game run for days and now when I leave my afk spot I find hundreds of zombees and skeleton bees I lag like crazy. I tried using the kill command but they are not in the list to kill.please give command to kill before I need to start over.

### How to Reproduce?

Easy have hives open for days irl and run from afk spot.

### Expected Behavior

Kill command to kill but can't find in list.

### Version

All the mods 9

### Mod Loader Version

All the mods 9

### Acknowledgement

- [X] I agree that I read the terms at the top of the page.

**Comment by ThatGravyBoat** [comment]
You are looking for productive bees not resourceful bees
